server:
  port: 8082
  servlet:
    session:
      timeout: -1
spring:
  application:
    name: iot-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

redis:
 pubsub:
  channel:
   name : device_data